#!/bin/bash

echo Successfully install daibutsu afc2d!

declare -a cydia
cydia=($CYDIA)
firmware=$(sw_vers -productVersion)

if [[ ${CYDIA+@} ]]; then
   eval "echo 'finish:reboot' >&${cydia[0]}"
fi

echo
